{% set name = "filecache" %}
{% set version = "0.81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be071ad64937b51f38b03ecd82b9b68c08d0f570cdddb30aa8f90150fe54b30a
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - filecache
  source_files:
    - filecache/test
  commands:
    - python filecache/test/test_filecache.py

about:
  home: https://github.com/ubershmekel/filecache
  summary: 'Persistent caching decorator'
  description: |
    filecache
    filecache is a decorator which saves the return value of functions even
    after the interpreter dies. For example this is useful on functions that download
    and parse webpages. All you need to do is specify how long
    the return values should be cached (use seconds, like time.sleep).
    
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - theAeon
